# Generated by Django 4.2.3 on 2023-07-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
